/*
 * Swirepay
 * Swirepay REST APIs' are resource-oriented URLs that accept JSON-encoded request bodies, return JSON-encoded responses, and use standard HTTP response codes, authentication, and verbs. You can use the Swirepay API in test mode, which does not affect your live data or interact with the banking networks. The `API key` you use to authenticate the request determines whether the request is live mode or test mode.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swirepay.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InlineResponse2004;
import io.swagger.client.model.InlineResponse2005;
import io.swagger.client.model.PaymentMethodRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PaymentMethodApi
 */
@Ignore
public class PaymentMethodApiTest {

    private final PaymentMethodApi api = new PaymentMethodApi();

    /**
     * Add a payment method
     *
     * Adds a payment method to an account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addPaymentMethodTest() throws ApiException {
        PaymentMethodRequest body = null;
        String xApiKey = null;
        InlineResponse2005 response = api.addPaymentMethod(body, xApiKey);

        // TODO: test validations
    }
    /**
     * Get payment methods
     *
     * Get payment methods
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPaymentMethodTest() throws ApiException {
        String xApiKey = null;
        InlineResponse2004 response = api.getPaymentMethod(xApiKey);

        // TODO: test validations
    }
}
